satellites:
  METEOR-M2 3:
    enabled: true
    frequency: 137900000
    mode: LRPT
    pipeline: meteor_m2-x_lrpt
    decoder: satdump
    sample_rate: 1000000
    min_elevation: 54.0
    priority: 1
  METEOR-M2 4:
    enabled: true
    frequency: 137900000
    mode: LRPT
    pipeline: meteor_m2-x_lrpt
    decoder: satdump
    sample_rate: 1000000
    min_elevation: 54.0
    priority: 1
