station:
  name: SDRCC
  version: 0.3.1
  location: Vlaardingen
  latitude: 51.908401
  longitude: 4.351168
  altitude_m: 6

sdr1:
  serial: "05419737"
  name: "AIS Receiver"
  task: "ais"
  locked: true

sdr2:
  serial: "24006572"
  name: "Dynamic Receiver"
  task: "weather"
  locked: false
