station:
  name: SDRCC
  version: 0.3.1
  location: Vlaardingen
  latitude: 51.908401
  longitude: 4.351168
  altitude_m: 6
sdr1:
  serial: 05419737
  name: AIS Receiver
  task: ais
  locked: true
sdr2:
  serial: '24006572'
  name: Dynamic Receiver
  task: weather
  locked: false
assignments:
  weather: sdr1
  ais: sdr1
  adsb: sdr2
weather_rf:
  gain_mode: auto
  gain_db: 38.6
  dc_block: true
  iq_swap: false
  spectrum_span_hz: 1000000
  spectrum_bin_hz: 10000
automation_policy:
  auto_preflight: true
  reserve_receiver: true
  prepare_sdr: true
  start_recording: true
  start_satdump: true
  process_images: true
  archive_mission: true
  restore_services: true
