station:
  name: SDRCC
  version: 0.3.1
  location: Vlaardingen
  latitude: 51.908401
  longitude: 4.351168
  altitude_m: 6
sdr1:
  serial: 05419737
  name: AIS Receiver
  locked: true
sdr2:
  serial: '24006572'
  name: Dynamic Receiver
  locked: false
assignments:
  weather: sdr1
  ais: sdr1
  adsb: sdr2
weather_rf:
  gain_mode: manual
  gain_db: 38.6
  dc_block: false
  iq_swap: false
  spectrum_span_hz: 1000000
  spectrum_bin_hz: 10000
weather_planning:
  minimum_elevation: 54.0
